### ISSUE TITLE
Where is the 'Core' directory?

### ISSUE THREAD

**Issue by amyamadea** [manishjoy/magento2-catalog-infinite-scroll#1]
On 'Version.php', that class is extends from \TheCodingTutor\Core\Block\Adminhtml\System\Config\Form\Version. 
But I can't find the 'Core'.

**Comment by manishjoy** [comment]
Here it is: https://github.com/manishjoy/thecodingtutor-core

**Comment by amyamadea** [comment]
thanks :)

**Comment by manishjoy** [comment]
welcome @amyamadea
