### ISSUE TITLE
jquery issue in category page after infinitescroll

### ISSUE THREAD

**Issue by VK00481136** [manishjoy/magento2-catalog-infinite-scroll#3]
Hi Team,

Ajax Add to cart, Ajax add to wishlist and quickview are not working after loading products via infinite scroll in category page

No JS seems working. Kindly assist

Thanks in advance!

Regards,
Loganayaki k

**Comment by manishjoy** [comment]
The module seems to be working fine. But as you are using multiple custom modules, then you need to do customization to these modules as well to make them compatible with each-other

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by manishjoy** [comment]
I am closing this issue as didn't hear from you on this issue since long.
